[virtualenvs]
in-project = true

[solver]
# Set min-release-age to 2 weeks, same as in https://github.com/ni/python-renovate-config
min-release-age = 14
min-release-age-exclude = [
    "hightime",
    "ni-grpcdevice-v1-proto",
    "ni-protobuf-types",
    "ni-python-styleguide",
    "nitypes",
]
