name: nidaqmxbot_win_64

on:
  pull_request:
    branches:
      - master
jobs:
  run-system-tests-python-64bit:
    runs-on:
      - self-hosted
      - windows
      - x64
      - rdss-nidaqmxbot-win-10-py64
    timeout-minutes: 80
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: poetry install
      - name: Run system tests
        run: poetry run tox