name: nidaqmxbot_win_32

on:
  pull_request:
    branches:
      - master
jobs:
  do-the-job1:    
    run-system-tests-python-32bit:
      runs-on:
        - self-hosted
        - windows
        - x86
        - rdss-nidaqmxbot-win-10-py32
      timeout-minutes: 80
      steps:
        - name: checkout repository
          uses: actions/checkout@v3
        - name: Install dependencies
          run: poetry install
        - name: Run system tests
          run: poetry run tox